- name: "User '{{ ivar_user }}': Creating local account"
  user:
    name: "{{ ivar_user }}"
    shell: /bin/bash

#-------------------------------------------------------------------------------

- name: "User '{{ ivar_user }}': Managing group memberships"
  user:
    name: "{{ ivar_user }}"
    groups: "{{ item }}"
    append: yes
  with_items: "{{ ivar_metadata.get('groups', []) }}"

- name: "User '{{ ivar_user }}': Detecting current group memberships"
  command: "groups {{ ivar_user }}"
  register: current_group_memberships
  changed_when: False
  check_mode: No

- debug: var=current_group_memberships
  tags:
    - debug

- name: "User '{{ ivar_user }}': Setting fact - current group memberships"
  set_fact:
    current_group_list: "{{ current_group_memberships.stdout.replace(ivar_user+' : ', '').split(' ') }}"

- debug: var=current_group_list
  tags:
    - debug

- name: "User '{{ ivar_user }}': Removing extra group memberships"
  command: "deluser {{ ivar_user }} {{ item }}"
  loop: "{{ current_group_list }}"
  when: ivar_metadata.get('groups_remove_extra', False) and item != 'sudo' and item != ivar_user and item not in ivar_metadata.get('groups', [])

#-------------------------------------------------------------------------------

- name: "User '{{ ivar_user }}': Managing home directory permissions"
  file:
    path: "/home/{{ ivar_user }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0750
    state: directory

#-------------------------------------------------------------------------------

- name: "User '{{ ivar_user }}': Managing .ssh directory"
  file:
    path: "/home/{{ ivar_user }}/.ssh"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0700
    state: directory

- name: "User '{{ ivar_user }}': Managing SSH keys"
  template:
    src: "{{ item }}"
    dest: "/home/{{ ivar_user }}/.ssh/authorized_keys"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/user_files/{{ ivar_user }}/honzamach.accounts/authorized_keys.j2"
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.accounts/authorized_keys.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.accounts/authorized_keys.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.accounts/authorized_keys.j2"
    - "inventory/group_files/servers/honzamach.accounts/authorized_keys.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.accounts/authorized_keys.j2"
    - "authorized_keys.{{ ansible_lsb['codename'] }}.j2"
    - "authorized_keys.j2"

#-------------------------------------------------------------------------------

- name: "User '{{ ivar_user }}': Manage user home subdirectories"
  file:
    path: "/home/{{ ivar_user }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
  with_filetree:
    - "inventory/user_files/{{ ivar_user }}/honzamach.accounts/home/"
    - "inventory/user_files/all/honzamach.accounts/home/"
  when: item.state == 'directory'

- name: "User '{{ ivar_user }}': Manage user home files"
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ivar_user }}/{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
  with_filetree:
    - "inventory/user_files/{{ ivar_user }}/honzamach.accounts/home/"
    - "inventory/user_files/all/honzamach.accounts/home/"
  when: item.state == 'file'
